/* 
 * SwaggerCodegen.ExampleAPI
 *
 * A basic sample API for testing swagger CodeGen
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ItemsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ItemsApiTests
    {
        private ItemsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ItemsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ItemsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ItemsApi
            //Assert.IsInstanceOfType(typeof(ItemsApi), instance, "instance is a ItemsApi");
        }

        /// <summary>
        /// Test ApiItemsIdDelete
        /// </summary>
        [Test]
        public void ApiItemsIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //instance.ApiItemsIdDelete(id);
            
        }
        /// <summary>
        /// Test ApiItemsIdGet
        /// </summary>
        [Test]
        public void ApiItemsIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.ApiItemsIdGet(id);
            //Assert.IsInstanceOf<Item> (response, "response is Item");
        }
        /// <summary>
        /// Test ApiItemsPost
        /// </summary>
        [Test]
        public void ApiItemsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Item body = null;
            //var response = instance.ApiItemsPost(body);
            //Assert.IsInstanceOf<Item> (response, "response is Item");
        }
        /// <summary>
        /// Test ApiItemsPut
        /// </summary>
        [Test]
        public void ApiItemsPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Item body = null;
            //instance.ApiItemsPut(body);
            
        }
    }

}
